yatube/about/urls.py
from django.urls import path

from . import views


app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = "posts"

urlpatterns = [
    # Главная страница
    path("", views.index, name="index"),
    # Отдельная страница с информацией о group
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    # Профайл пользователя
    path("profile/<str:username>/", views.profile, name="profile"),
    # Просмотр записи
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    # New post
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:pk>/edit/", views.post_edit, name="post_edit"),
    path(
        "posts/<int:post_id>/comment/", views.add_comment, name="add_comment"
    ),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
    path("", include("posts.urls", namespace="posts")),
]

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField("имя", max_length=200)
    slug = models.SlugField("адрес", unique=True)
    description = models.TextField("описание")

    class Meta:
        verbose_name = "Groups, it will be shown in admin panel"

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField("заголовок")
    pub_date = models.DateTimeField("дата публикации", auto_now_add=True)
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
        verbose_name="сообщество",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="автор",
    )
    image = models.ImageField("Картинка", upload_to="posts/", blank=True)

    class Meta:
        verbose_name = "Posts, it will be shown in admin panel"
        ordering = (
            "pk",
            "-pub_date",
        )

    def __str__(self):
        return self.text


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="комментарии",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="автор",
    )
    text = models.TextField("текст комментария")
    created = models.DateTimeField("дата комментария", auto_now_add=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="кто подписывается",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="на кого подписываютс",
    )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            "text",
            "group",
            "image",
        )
        help_texts = {
            "text": "Text for new post",
            "group": "Group's post",
            "image": "pickup the picture",
        }

    def clean_text(self):
        data = self.cleaned_data["text"]
        if not data:
            raise forms.ValidationError("Please fill empty field")
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.checks.messages import Error
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm, CommentForm
from .models import Group, Post, Comment, Follow

User = get_user_model()


def index(request):
    post_list = Post.objects.all()
    title = "Последние обновления на сайте"
    paginator = Paginator(post_list, settings.DEFAULT_POSTS_ON_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj": page_obj,
        "title": title,
        "post_list": post_list,
    }
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group)
    paginator = Paginator(post_list, settings.DEFAULT_POSTS_ON_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    title = group.title
    description = group.description
    context = {
        "page_obj": page_obj,
        "title": title,
        "description": description,
        "post_list": post_list,
    }
    return render(request, "posts/group_list.html", context)


def profile(request, username):
    author = User.objects.get(username=username)
    post_list = Post.objects.filter(author=author)
    author_name = username
    post_all = Post.objects.filter(author=author).count()
    paginator = Paginator(post_list, settings.DEFAULT_POSTS_ON_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    if request.user.is_anonymous:
        following = False
    else:
        try:
            Follow.objects.get(user=request.user, author=author)
        except Follow.DoesNotExist:
            following = False
        else:
            following = True

    context = {
        "page_obj": page_obj,
        "post_list": post_list,
        "post_all": post_all,
        "author_name": author_name,
        "author": author,
        "following": following,
    }
    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    post_list = Post.objects.all()
    post_all = Post.objects.filter(author=author).count()
    form = CommentForm()
    comments = Comment.objects.filter(post=post_id)
    context = {
        "post": post,
        "post_all": post_all,
        "post_list": post_list,
        "comments": comments,
        "form": form,
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:profile", username=request.user.username)
    return render(request, "posts/create_post.html", {"form": form})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:
        return redirect("posts:post_detail", post_id=pk)

    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=post
    )
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id=pk)
    context = {
        "post": post,
        "form": form,
        "is_edit": True,
    }
    return render(request, "posts/create_post.html", context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request):
    # информация о текущем пользователе доступна в переменной request.user
    try:
        follow_obj = Follow.objects.get(user=request.user)
    except:
        return render(request, "core/404.html")
    else:
        post_list = Post.objects.filter(author=follow_obj.author)
    title = "Посты на которые вы подписаны"
    paginator = Paginator(post_list, settings.DEFAULT_POSTS_ON_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj": page_obj,
        "title": title,
        "post_list": post_list,
    }
    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.create(user=request.user, author=author)
    return redirect("posts:profile", username)


@login_required
def profile_unfollow(request, username):
    # Дизлайк, отписка
    author = get_object_or_404(User, username=username)
    follow_obj = Follow.objects.get(user=request.user, author=author)
    follow_obj.delete()
    return redirect("posts:profile", username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
  Edit
{% else %}
  New post
{% endif %}   
{% endblock %}
{% block content %}
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}   
                Редактировать
                {% else %}
                Новый пост
                {% endif %} 
              </div>
              <div class="card-body">        
                <form method="post" enctype="multipart/form-data" {% if is_edit %} action="{% url 'posts:post_edit' pk=post.pk %}" {% else %} action="{% url 'posts:post_create' %}"{% endif %}>
                  {% csrf_token %}          
                  <div class="form-group row my-3 p-3">
                    {{ form }}
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}               
                    </button> 
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <div class="container py-5">     
    <h1>{{ title }}</h1>
    {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <a href="{%url 'posts:post_detail' post.id %}">подробная информация </a>  
      </article>
      {% if post.group %}  
        <a href="{%url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}  
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %} 
  </div> 
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>Записи сообщества {{ title }}</h1>
  <p>{{ description }}</p>
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
        </li>
        <li>
           Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href="{%url 'posts:post_detail' post.id %}">подробная информация </a>
    </article>
      {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %} 
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %} 
  </div>  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <div class="container py-5">     
    <h1>{{ title }}</h1>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>
          {{ post.text }}
        </p>
        {% if post.group %}  
          <a href="{%url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}  
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}
  Пост {{ post.text|slice:":30" }}
{% endblock %}
{% block content %}
    <main>
      <div class="container py-5">
        <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
              {% if post.group %}  
              <li class="list-group-item">
                Группа: {{ group }}
                <a href="{%url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
              </li>
              {% endif %}
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post_all }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author%}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>  
            {{ post.text }}
          </p>
          <a class="btn btn-primary" href="{% url 'posts:post_edit' pk=post.pk %}">
            редактировать запись
          </a>
          {% include 'includes/comments.html' %}  
        </article>        
      </div>
    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Профайл пользователя {{ author_name }}
{% endblock %}
{% block content %} 
    <main>
      <div class="container py-5">        
        <div class="mb-5">
          <h1>Все посты пользователя {{ author.get_full_name }}</h1>
          <h3>Всего постов: {{ post_all }}</h3>
          {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
              Отписаться
            </a>
          {% else %}
              <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button"
              >
                Подписаться
              </a>
           {% endif %}
        </div> 
        {% for post in page_obj %}
         <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' author_name %}">все посты пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
             {{ post.text }}
            </p>
            <a href="{%url 'posts:post_detail' post.id %}">подробная информация </a>
          </article>          
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}   
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %} 
      </div>
    </main>
{% endblock %}